### ISSUE TITLE
Cannot configure template rendering.

### ISSUE THREAD

**Issue by ivok** [netglue/Zend-Expressive-Mail-Template#1]
I have problems about Template Rendering.

The PhpRenderer allways says 

" Zend\View\Renderer\PhpRenderer::render: Unable to render template "error::error"; resolver could not resolve to a file in "

What you mean by this "Clearly, you'll also need to setup your template resolver to know where to find these template names:" How to setup the resolver?

Also I think that a dependecy is missing. I should installed aditionaly the "zendframework/zend-expressive-zendviewrenderer".

**Comment by gsteel** [comment]
When you setup a new expressive project, this lib assumes you already have a renderer/templating service configured. Normally, this will be Twig, Plates or Zend View. [zendframework/zend-expressive-template](https://github.com/zendframework/zend-expressive-template) is already a dependency, but you'll need to require [zendframework/zend-expressive-zendviewrenderer](https://github.com/zendframework/zend-expressive-zendviewrenderer) to and then read up on the docs for how expressive templates are configured

**Comment by ivok** [comment]
In our expressive project, we didnt use zend-view and should install it. Also, my mistake was that in the templates configuration, didnt add error::error and layout:default mapping, so Renderer promted this error.
